spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/carparking}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:paodepovilho2003}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect